### PR TITLE
Displaying the country when entering the server and adding NULL checks

### PR DESCRIPTION
**Pull request by ZIFON**

### CODE REVIEW

**Comment by ZIFON** [comment]
Протести, я просто не тестировал просто добавил отображение стран при входе и проверки на NULL
Если что пиши

**Comment by ZIFON** [comment]
Делай версии на гите чтобы можно было потом откат сделать

**Comment by Klayeryt** [comment]
Ок, немного позже протестирую, спасибо

**Comment by ZIFON** [comment]
файл GeoLite2-Country.mmdb еще нужно закинуть в папку plugins

**Comment by Klayeryt** [comment]
Понял. Сорян, но только в течении двух дней только смогу проверить, не большие проблемы с ОС. Как решу сразу проверю

**Comment by ZIFON** [comment]
ok

**Comment by Klayeryt** [comment]
Ошибка, предположу ему нужна сама библиотека MaxMind.GeoIP2

16:57:45 [ERROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'MaxMind.GeoIP2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=66afa4cc5ae853ac'. Не удается найти указанный файл.
File name: 'MaxMind.GeoIP2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=66afa4cc5ae853ac'
   at Main.Main.GetCountry(String ipAddress)
   at Main.Main.OnPlayerConnectFull(EventPlayerConnectFull event, GameEventInfo info) in E:\csgotestserver\steamapps\common\Counter-Strike Global Offensive\game\csgo\addons\counterstrikesharp\source\WelcomeVersion\Main.cs:line 89
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by Klayeryt** [comment]
Ошибка, думаю ему нужна MaxMinds.dll

17:00:32 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'MaxMind.GeoIP2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=66afa4cc5ae853ac'. Не удается найти указанный файл.
File name: 'MaxMind.GeoIP2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=66afa4cc5ae853ac'
   at Main.Main.GetCountry(String ipAddress)
   at Main.Main.OnPlayerConnectFull(EventPlayerConnectFull event, GameEventInfo info) in E:\csgotestserver\steamapps\common\Counter-Strike Global Offensive\game\csgo\addons\counterstrikesharp\source\WelcomeVersion\Main.cs:line 89
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by Klayeryt** [comment]
22:13:45 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> MaxMind.GeoIP2.Exceptions.AddressNotFoundException: The address 127.0.0.1 is not in the database.
   at MaxMind.GeoIP2.DatabaseReader.Execute[T](String ipStr, IPAddress ipAddress, String type, Boolean throwOnNullResponse)
   at MaxMind.GeoIP2.DatabaseReader.Country(String ipAddress)
   at Main.Main.GetCountry(String ipAddress) in E:\csgotestserver\steamapps\common\Counter-Strike Global Offensive\game\csgo\addons\counterstrikesharp\source\WelcomeVersion\Main.cs:line 78
   at Main.Main.OnPlayerConnectFull(EventPlayerConnectFull event, GameEventInfo info) in E:\csgotestserver\steamapps\common\Counter-Strike Global Offensive\game\csgo\addons\counterstrikesharp\source\WelcomeVersion\Main.cs:line 89
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by ZIFON** [comment]
Я так понимаю ошибка возникает из-за попытки поиска геолокации для IP-адреса 127.0.0.1, который не содержится в базе данных MaxMind GeoIP2
Чучуть позже исправлю

**Comment by ZIFON** [comment]
Посмотри еще правильно ли ты закинул все на сервер
Вот пример:
Снимок экрана 2024-07-29 173233

**Comment by ZIFON** [comment]
У тебя ошибка  возникает потому, что сервер пытается определить геолокацию для локального IP-адреса, такого как 127.0.0.1. Локальные IP-адреса не содержатся в базе данных GeoIP, потому что они предназначены для использования внутри частных сетей и не имеют соответствующего географического расположения.
Если игрок подключается к локальному серверу, его IP-адрес может быть 127.0.0.1, а его в базе нету
Попробуй залить на хостинг, я могу добавить проверну на локальный сервер но что бы плагин зароботал он должен быть на хостинге

**Comment by Klayeryt** [comment]
К сожалению возможности протестировать на хостинге у меня нету, всё тестирую на локалке

**Comment by ZIFON** [comment]
Ок, я сам тогда посмотрю

**Pull request merged**
